// ═══════════════════════════════════════════════════════════════════
// charEdge — Footprint Renderer
// Specialized canvas renderer for Volume Delta Footprints
// ═══════════════════════════════════════════════════════════════════

import { C, F, M } from '../../constants.js';

export class FootprintRenderer {
  /**
   * Render footprint data inside the candle area
   * @param {CanvasRenderingContext2D} ctx
   * @param {Object} bar - OHLCV object with attached .footprint generated by OrderFlowAggregator
   * @param {number} x - Pixel X coordinate center of the bar
   * @param {number} yOpen - Pixel Y for Open
   * @param {number} yClose - Pixel Y for Close
   * @param {number} yHigh - Pixel Y for High
   * @param {number} yLow - Pixel Y for Low
   * @param {Function} priceToY - Function mapping a price down to a Y pixel coordinate
   * @param {number} barWidth - Allocated width in pixels for this bar
   */
  static draw(ctx, bar, x, yOpen, yClose, yHigh, yLow, priceToY, barWidth) {
    const isUp = bar.close >= bar.open;
    const bodyColor = isUp ? C.g : C.r;

    // 1. Draw the basic hollow/filled background candle outline
    // Draw Wick
    ctx.strokeStyle = bodyColor;
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(x, yHigh);
    ctx.lineTo(x, yLow);
    ctx.stroke();

    // Draw Body Outline (always hollow to leave room for text)
    const bodyY = Math.min(yOpen, yClose);
    const bodyH = Math.max(Math.abs(yClose - yOpen), 1);
    const w = Math.max(barWidth * 0.8, 1);

    ctx.fillStyle = C.bg;
    ctx.fillRect(x - w / 2, bodyY, w, bodyH);
    ctx.strokeRect(x - w / 2, bodyY, w, bodyH);

    // If footprint data doesn't exist or we are zoomed too far out, skip text rendering
    if (!bar.footprint || barWidth < 30) {
      return;
    }

    // 2. Render the Footprint (Bid x Ask) text
    ctx.font = `10px ${M}`;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';

    let maxCellVol = 0;
    for (const p in bar.footprint) {
      if (bar.footprint[p].totalVol > maxCellVol) {
        maxCellVol = bar.footprint[p].totalVol;
      }
    }

    const prices = Object.keys(bar.footprint).map(Number).sort((a,b) => b - a);

    prices.forEach(p => {
      const data = bar.footprint[p];
      const pY = priceToY(p);

      // Calculate intensity for background shading (opacity based on volume relative to max)
      const intensity = Math.min((data.totalVol / maxCellVol) * 0.5, 0.8);

      // Left side: Bid Volume
      ctx.fillStyle = `rgba(255, 100, 100, ${intensity})`; // Reddish for selling
      ctx.fillRect(x - w/2, pY - 6, w/2, 12);

      // Right side: Ask Volume
      ctx.fillStyle = `rgba(100, 255, 100, ${intensity})`; // Greenish for buying
      ctx.fillRect(x, pY - 6, w/2, 12);

      // Draw Text
      // Format: Bid x Ask
      // We shrink font slightly if we need more horizontal room
      if (barWidth >= 60) {
        // Draw separate if we have room
        ctx.fillStyle = C.t1;
        ctx.textAlign = 'right';
        ctx.fillText(data.bidVol.toFixed(1), x - 2, pY);

        ctx.textAlign = 'left';
        ctx.fillText(data.askVol.toFixed(1), x + 2, pY);
      } else {
        // Draw combined if tight
        ctx.fillStyle = C.t1;
        ctx.textAlign = 'center';
        ctx.fillText(`${data.bidVol.toFixed(0)}x${data.askVol.toFixed(0)}`, x, pY);
      }
    });

    // 3. Highlight Point of Control (POC) for this bar
    if (bar.poc !== null) {
      const pocY = priceToY(bar.poc);
      ctx.strokeStyle = C.y; // Bright yellow border for POC
      ctx.lineWidth = 1;
      ctx.strokeRect(x - w/2, pocY - 6, w, 12);
    }
  }
}
