// ═══════════════════════════════════════════════════════════════════
// charEdge — Trade Documentation Generator (Sprint 84)
//
// Auto-generates structured trade reports for review or sharing.
// Routes through AIRouter for narrative generation.
//
// Usage:
//   import { tradeDocGenerator } from './TradeDocGenerator';
//   const doc = await tradeDocGenerator.generate(trade, journalNotes);
// ═══════════════════════════════════════════════════════════════════

// ─── Types ───────────────────────────────────────────────────────

export interface TradeDoc {
  title: string;
  markdown: string;
  sections: {
    setup: string;
    entry: string;
    management: string;
    exit: string;
    lessons: string;
  };
  metadata: {
    symbol: string;
    date: string;
    pnl: number;
    tier: string;
  };
}

// ─── Generator ──────────────────────────────────────────────────

class TradeDocGenerator {
  /**
   * Generate a structured trade report.
   */
  async generate(
    trade: Record<string, unknown>,
    journalNotes: string = '',
  ): Promise<TradeDoc> {
    const symbol = String(trade.symbol || '?');
    const side = String(trade.side || '?');
    const pnl = typeof trade.pnl === 'number' ? trade.pnl : 0;
    const entry = trade.entryPrice || '?';
    const exit = trade.exitPrice || '?';
    const setup = trade.setupType || 'Unknown';
    const emotion = trade.emotion || 'Not noted';
    const date = this._formatDate(trade.date || trade.entryTime);

    const prompt = `Generate a structured trade report in markdown format.

Trade Details:
- Symbol: ${symbol}
- Direction: ${side}
- Entry: $${entry}
- Exit: $${exit}
- P&L: $${pnl.toFixed(2)}
- Setup: ${setup}
- Emotion: ${emotion}
- Date: ${date}

${journalNotes ? `Journal Notes:\n${journalNotes}` : ''}

Format with these sections:
## Setup
What was the setup? Why was this trade taken?

## Entry
How was the entry executed? Was it well-timed?

## Management
How was the position managed during the trade?

## Exit
How and why was the trade exited?

## Lessons
What can be learned from this trade?

Keep each section to 1-2 sentences. Be specific and reference the actual numbers.`;

    try {
      const { aiRouter } = await import('./AIRouter');
      const result = await aiRouter.route({
        type: 'coach',
        messages: [
          { role: 'system', content: 'You are a trading performance analyst writing structured trade reports. Be specific, reference actual trade data. Use markdown.' },
          { role: 'user', content: prompt },
        ],
        maxTokens: 400,
        temperature: 0.3,
      });

      return {
        title: `${symbol} ${side} — ${date}`,
        markdown: result.content,
        sections: {
          setup: this._extractSection(result.content, 'Setup'),
          entry: this._extractSection(result.content, 'Entry'),
          management: this._extractSection(result.content, 'Management'),
          exit: this._extractSection(result.content, 'Exit'),
          lessons: this._extractSection(result.content, 'Lessons'),
        },
        metadata: { symbol, date, pnl, tier: result.tier },
      };
    } catch {
      return this._fallbackDoc(symbol, side, entry, exit, pnl, date, setup);
    }
  }

  /**
   * Copy trade doc to clipboard.
   */
  async copyToClipboard(doc: TradeDoc): Promise<boolean> {
    try {
      const text = `# ${doc.title}\n\n${doc.markdown}\n\n---\n*Generated by charEdge*`;
      await navigator.clipboard.writeText(text);
      return true;
    } catch {
      return false;
    }
  }

  // ─── Helpers ─────────────────────────────────────────────────

  private _extractSection(text: string, header: string): string {
    const regex = new RegExp(`##\\s*${header}[\\s\\n]+(.*?)(?=##|$)`, 'is');
    const match = text.match(regex);
    return match ? match[1].trim() : '';
  }

  private _formatDate(v: unknown): string {
    if (!v) return new Date().toISOString().split('T')[0];
    const d = new Date(typeof v === 'number' ? v : String(v));
    return isNaN(d.getTime()) ? 'Unknown' : d.toISOString().split('T')[0];
  }

  private _fallbackDoc(
    symbol: string, side: string, entry: unknown, exit: unknown,
    pnl: number, date: string, setup: unknown,
  ): TradeDoc {
    const markdown = `## Setup\n${setup} setup on ${symbol}\n\n## Entry\n${side} at $${entry}\n\n## Exit\nClosed at $${exit} for ${pnl >= 0 ? 'profit' : 'loss'} of $${pnl.toFixed(2)}\n\n## Lessons\nReview this trade to identify patterns.`;
    return {
      title: `${symbol} ${side} — ${date}`,
      markdown,
      sections: {
        setup: `${setup} setup on ${symbol}`,
        entry: `${side} at $${entry}`,
        management: '',
        exit: `Closed at $${exit}`,
        lessons: 'Review this trade.',
      },
      metadata: { symbol, date, pnl, tier: 'L1' },
    };
  }
}

// ─── Singleton ──────────────────────────────────────────────────

export const tradeDocGenerator = new TradeDocGenerator();
export default tradeDocGenerator;
