// ═══════════════════════════════════════════════════════════════════
// charEdge — AI Brief Card (Sprint 76)
//
// Dashboard widget for the AI Morning Briefing.
// ═══════════════════════════════════════════════════════════════════

import { useState, useCallback, useEffect } from 'react';
import { C } from '../../../constants.js';
import AIStreamText from './AIStreamText.jsx';

const ACCENT = '#6e5ce6';

export default function AIBriefCard() {
  const [brief, setBrief] = useState(null);
  const [loading, setLoading] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);

  const generateBrief = useCallback(async () => {
    setLoading(true);
    try {
      const { aiBriefService } = await import('../../../ai/AIBriefService');
      // Get watchlist from store if available
      let watchlist = [];
      try {
        const mod = await import('../../../state/useWatchlistStore');
        const store = mod.useWatchlistStore || mod.default;
        if (store?.getState) {
          const state = store.getState();
          watchlist = (state.symbols || state.watchlist || [])
            .map((s) => (typeof s === 'string' ? s : s.symbol || s.id || ''))
            .filter(Boolean);
        }
      } catch {
        /* no watchlist store */
      }

      const result = await aiBriefService.generate(watchlist);
      setBrief(result);
    } catch {
      setBrief({ marketOverview: 'Failed to generate brief.', raw: '', tier: 'L1', generatedAt: Date.now() });
    } finally {
      setLoading(false);
    }
  }, []);

  // Auto-generate on mount if not yet done today
  useEffect(() => {
    if (!autoGenerated) {
      setAutoGenerated(true);
      // Check if cached brief exists
      try {
        const cached = localStorage.getItem('charEdge-morning-brief');
        if (cached) {
          const parsed = JSON.parse(cached);
          const today = new Date().toISOString().split('T')[0];
          const briefDay = new Date(parsed.generatedAt).toISOString().split('T')[0];
          if (briefDay === today) {
            setBrief(parsed);
            return;
          }
        }
      } catch {
        /* */
      }
    }
  }, [autoGenerated]);

  return (
    <div
      style={{
        background: C.bg2 || C.bg,
        border: `1px solid ${C.bd}`,
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
      }}
    >
      {/* Header */}
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginBottom: 12,
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{ fontSize: 16 }}>☀️</span>
          <span
            style={{
              fontSize: 13,
              fontWeight: 700,
              fontFamily: 'var(--tf-font)',
              color: C.t1,
            }}
          >
            Morning Brief
          </span>
        </div>
        <button
          onClick={generateBrief}
          disabled={loading}
          style={{
            padding: '4px 12px',
            borderRadius: 6,
            border: `1px solid ${ACCENT}40`,
            background: loading ? `${C.bd}20` : `${ACCENT}15`,
            color: ACCENT,
            fontSize: 10,
            fontFamily: 'var(--tf-mono)',
            cursor: loading ? 'wait' : 'pointer',
          }}
        >
          {loading ? '⏳ Generating...' : brief ? '🔄 Refresh' : '✨ Generate'}
        </button>
      </div>

      {/* Content */}
      {!brief && !loading && (
        <div
          style={{
            textAlign: 'center',
            padding: '12px 0',
            color: C.t3,
            fontSize: 11,
            fontFamily: 'var(--tf-mono)',
          }}
        >
          Click "Generate" for your pre-market AI briefing.
        </div>
      )}

      {brief && (
        <div>
          {brief.marketOverview && <AIStreamText text={brief.marketOverview} />}

          {brief.watchlistMoves?.length > 0 && (
            <div style={{ margin: '8px 0', display: 'flex', flexWrap: 'wrap', gap: 6 }}>
              {brief.watchlistMoves.map((m) => (
                <span
                  key={m.symbol}
                  style={{
                    padding: '2px 8px',
                    borderRadius: 4,
                    background: m.change > 0 ? '#4ade8020' : '#ef444420',
                    color: m.change > 0 ? '#4ade80' : '#ef4444',
                    fontSize: 10,
                    fontFamily: 'var(--tf-mono)',
                  }}
                >
                  {m.symbol} {m.change > 0 ? '+' : ''}
                  {m.change.toFixed(1)}%
                </span>
              ))}
            </div>
          )}

          {brief.focusTrades && (
            <div style={{ marginTop: 8 }}>
              <div
                style={{ fontSize: 10, fontWeight: 700, fontFamily: 'var(--tf-font)', color: C.t2, marginBottom: 4 }}
              >
                🎯 Focus
              </div>
              <AIStreamText text={brief.focusTrades} />
            </div>
          )}

          {brief.tier && (
            <div style={{ marginTop: 8, fontSize: 8, fontFamily: 'var(--tf-mono)', color: C.t3 }}>
              Via {brief.tier} · {new Date(brief.generatedAt).toLocaleTimeString()}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
